[package]
name = "maptroid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ratatui = "0.27"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
